services:
  db:
    image: postgres:15
    restart: always
    container_name: nest_pg_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_games_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
